baseURL = "https://www.interchainglossary.io"
languageCode = "en-us"
title = "Interchain Glossary"
copyright = "MIT License, <a href='https://github.com/do-community/developer-glossary'>Contribute on GitHub</a>"

disableKinds = ["taxonomy", "term"]

buildFuture = true

[params]
  titleEmoji = ":tada:"
  description = "A glossary for the Interchain"

[Permalinks]
  term = ":slug"
